name: flutter_ecommerce_app
description: "Flutter Plan Shop App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  #icon
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  #font
  google_fonts: ^6.2.0

  #state management
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

  #local assets
  assets:
    - assets/icons
    - assets/logos
    - assets/images